default_stages: [ commit, manual ]

repos:


  # In order to be able to run the pip-audit hook correctly it is a must to have Poetry installed.
  - repo: https://github.com/trailofbits/pip-audit.git
    rev: v2.6.1
    hooks:
      - id: pip-audit
        entry: bash -c "poetry export --without-hashes | pip-audit --index-url https://pypi.artifacts.furycloud.io/simple/ --no-deps -r /dev/stdin --ignore PYSEC-2023-194"

  # Code formatter
  - repo: https://github.com/ambv/black
    rev: 23.10.0
    hooks:
      - id: black
        language_version: python3
        args:
          - --config
          - .code_quality/pyproject_black.toml

  # Style guide enforcement
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - --config=.code_quality/.flake8

  # Static code analyser
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.0.2
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        args:
          - --rcfile=.pylintrc



  # Common security issues analysis
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args:
          - -c
          - .code_quality/bandit.yaml

  # Static type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        args:
          - --config-file=.code_quality/mypy.ini
        additional_dependencies:
          - types-PyMySQL
          - types-requests
          - types-cachetools
          - types-pyyaml

  # Conventional commits
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
        args: [ ]
