class FieldNotFoundError(Exception): ...


class InvalidCrudType(Exception): ...


class InvalidModelParams(Exception): ...


class ScheduleAlreadyTaken(Exception): ...


class AppointmentNotFound(Exception): ...


class AgentNotFound(Exception): ...
